####
# Project-specific details & settings
####

TARGETS            = 

LIB_TARGETS        = libfilesystem

libfilesystem_OBJS = path.o \
                     directory_entry.o \
                     directory_iterator.o \
                     recursive_directory_iterator.o \
                     path_iterator.o \
                     fs_operations.o \
                     filesystem_error.o


ifndef TOPDIR
  TOPDIR            = ..
  include $(TOPDIR)/Makefile.include
endif

