TARGETS             = 
LIB_TARGETS         = libautomata
libautomata_HEADERS = 
libautomata_OBJS    =

driver_OBJS         = 
interval_OBJS       = 

ifndef TOPDIR
  TOPDIR            = ..
  include $(TOPDIR)/Makefile.include
endif
