TARGETS             = driver
LIB_TARGETS         = libautomata
libautomata_HEADERS = 
libautomata_OBJS    =

driver_OBJS         = driver.o $(libcodecvt_OBJS)

ifndef TOPDIR
  TOPDIR            = ..
  include $(TOPDIR)/Makefile.include
endif
